director_role_arn =  "${director_role_arn}"
pas_bucket_role_arn = "${pas_bucket_role_arn}"
om_role_arn = "${om_role_arn}"
bosh_role_arn = "${bosh_role_arn}"
sjb_role_arn = "${sjb_role_arn}"
concourse_role_arn = "${concourse_role_arn}"
bootstrap_role_arn = "${bootstrap_role_arn}"
foundation_role_arn = "${foundation_role_arn}"
