version: 2
updates:
- package-ecosystem: gomod
  open-pull-requests-limit: 25
  directory: modules/download_certs
  schedule:
    interval: weekly
    day: wednesday
    time: "00:01"
    timezone: EST5EDT
