#cloud-config
cloud_final_modules:
  - [users-groups,always]
users:
  - name: ubuntu
    groups: [ wheel ]
    sudo: [ "ALL=(ALL) NOPASSWD:ALL" ]
    shell: /bin/bash
    ssh-authorized-keys:
      - ssh-rsa <pub key>