variable "s3_logs_bucket" {}
variable "cloudwatch_audit_log_group_name" {}
variable "cloudwatch_log_group_name" {}
variable "cloudwatch_log_stream_name" {}
variable "s3_audit_logs_bucket" {}
variable "region" {}
variable "s3_path" {}
variable "loki_url" {}
variable "loki_username" {}
variable "loki_password" {}
