{
 "title": "AWS-ENA Network Performance",
 "description": "A dashbaord for monitoring AWS Elastic Network Adapter performance using the Prometheus Node exporter.",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "device",
    "label": "Interface:",
    "query": {
     "query": "label_values(node_ethtool_info{driver=\"ena\"}, device)"
    }
   },
   {
    "name": "node",
    "label": "Node Name",
    "query": {
     "query": "label_values(node_exporter_build_info, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Inbound Bandwidth Exceeded",
   "type": "stat",
   "description": "The number of packets queued or dropped because the inbound aggregate bandwidth exceeded the maximum for the instance since startup.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_ethtool_bw_in_allowance_exceeded{instance=~\"$node\", device=~\"$device\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Outbound Bandwidth Exceeded",
   "type": "stat",
   "description": "The number of packets queued or dropped because the outbound aggregate bandwidth exceeded the maximum for the instance since startup.",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_ethtool_bw_out_allowance_exceeded{instance=~\"$node\", device=~\"$device\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "PPS Allowance Exceeded",
   "type": "stat",
   "description": "The number of packets queued or dropped because the bidirectional PPS exceeded the maximum for the instance since startup",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_ethtool_pps_allowance_exceeded{instance=~\"$node\", device=~\"$device\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Connection Allowance Exceeded",
   "type": "stat",
   "description": "The number of packets dropped because connection tracking exceeded the maximum for the instance and new connections could not be established. This can result in packet loss for traffic to or from the instance.",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_ethtool_conntrack_allowance_exceeded{instance=~\"$node\", device=~\"$device\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Local Allowance Exceeded",
   "type": "stat",
   "description": "The number of packets dropped because the PPS of the traffic to local proxy services exceeded the maximum for the network interface. This impacts traffic to the DNS service, the Instance Metadata Service, and the Amazon Time Sync Service.",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_ethtool_linklocal_allowance_exceeded{instance=~\"$node\", device=~\"$device\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ENA Driver",
   "type": "stat",
   "description": "The ENA driver version as reported by ethtool.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_ethtool_info{instance=~\"$node\"}"
    }
   ]
  },
  { "title": "Bandwidth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Bandwidth Exceeded",
   "type": "timeseries",
   "description": "The inbound, outbound, and total network bandwidth.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~\"$node\", device=~\"$device\"}[1m])*8 + irate(node_network_transmit_bytes_total{instance=~\"$node\", device=~\"$device\"}[1m])*8",
     "legendFormat": "total {{instance}} {{ device }}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~\"$node\", device=~\"$device\"}[1m])*8",
     "legendFormat": "receive {{instance}}/{{ device }}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~\"$node\", device=~\"$device\"}[1m])*8",
     "legendFormat": "transmit {{instance}}/{{ device }}"
    }
   ]
  },
  {
   "title": "Bandwidth Exceeded Rate",
   "type": "timeseries",
   "description": "Rate of packets queued or dropped because the outbound aggregate bandwidth exceeded the maximum for the instance.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(node_ethtool_bw_in_allowance_exceeded{instance=~\"$node\", device=~\"$device\"}[1m])",
     "legendFormat": "bw_in_allowance_exceeded {{instance}}/{{ device }}"
    },
    {
     "expr": "irate(node_ethtool_bw_out_allowance_exceeded{instance=~\"$node\", device=~\"$device\"}[1m])",
     "legendFormat": "bw_out_allowance_exceeded {{instance}}/{{ device }}"
    }
   ]
  },
  { "title": "Packets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "PPS Exceeded",
   "type": "timeseries",
   "description": "The inbound, outbound, and total packets per second.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_packets_total{instance=~\"$node\", device=~\"$device\"}[1m]) + irate(node_network_transmit_packets_total{instance=~\"$node\", device=~\"$device\"}[1m])",
     "legendFormat": "total {{ device }}"
    },
    {
     "expr": "irate(node_network_receive_packets_total{instance=~\"$node\", device=~\"$device\"}[1m])",
     "legendFormat": "receive {{ device }}"
    },
    {
     "expr": "irate(node_network_transmit_packets_total{instance=~\"$node\", device=~\"$device\"}[1m])",
     "legendFormat": "transmit {{ device }}"
    }
   ]
  },
  {
   "title": "PPS Allowance Exceeded Rate",
   "type": "timeseries",
   "description": "Rate of packets queued or dropped because the bidirectional PPS exceeded the maximum for the instance.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(node_ethtool_pps_allowance_exceeded{instance=~\"$node\", device=~\"$device\"}[1m])",
     "legendFormat": "pps_allowance_exceeded {{instance}}/{{ device }}"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Established Connections",
   "type": "timeseries",
   "description": "The total number of established TCP connections.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=~\"$node\"}",
     "legendFormat": "connections {{ instance }}"
    }
   ]
  },
  {
   "title": "Connection Rate",
   "type": "timeseries",
   "description": "Rate of active and passive TCP connections being opened.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(node_netstat_Tcp_ActiveOpens{instance=~\"$node\"}[1m])",
     "legendFormat": "active {{instance}}"
    },
    {
     "expr": "rate(node_netstat_Tcp_PassiveOpens{instance=~\"$node\"}[1m])",
     "legendFormat": "passive {{instance}}"
    }
   ]
  }
 ]
}