{
 "title": "Cloudwatch Log Forwarder",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "Nozzle App",
    "query": "label_values(cloudwatch_forwarder_active_bindings, applicationGuid)"
   },
   {
    "name": "noisy_app",
    "label": "Noisy App",
    "query": "label_values(noisy_health, applicationGuid)"
   }
  ]
 },
 "panels": [
  { "title": "Forwarder", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Service Bindings",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(cloudwatch_forwarder_active_bindings)"
    }
   ]
  },
  {
   "title": "Event Buffer Length",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "avg(avg_over_time(cloudwatch_forwarder_output_buffer_queue_length{applicationGuid=\"${app}\"}[1m])) by (applicationGuid, forwarder_instance_index)",
     "legendFormat": "{{applicationGuid}}/{{forwarder_instance_index}}"
    }
   ]
  },
  {
   "title": "Sync Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(cloudwatch_forwarder_sync_time_bucket{applicationGuid=\"${app}\"}[5m])) by (applicationGuid, le))",
     "legendFormat": "{{applicationGuid}}/{{applicationInstance}} 95th"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(cloudwatch_forwarder_sync_time_bucket{applicationGuid=\"${app}\"}[5m])) by (applicationGuid, le))",
     "legendFormat": "{{applicationGuid}}/{{applicationInstance}} 50th"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(cloudwatch_forwarder_sync_time_bucket{applicationGuid=\"${app}\"}[5m])) by (applicationGuid, le))",
     "legendFormat": "{{applicationGuid}}/{{applicationInstance}} 99th"
    }
   ]
  },
  {
   "title": "Input Event Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cloudwatch_forwarder_input_num_events_total{applicationGuid=\"${app}\"}[1m])) by (applicationGuid, forwarder_instance_index)",
     "legendFormat": "{{applicationGuid}}/{{forwarder_instance_index}}"
    }
   ]
  },
  {
   "title": "Output Event Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cloudwatch_forwarder_output_num_events_total{applicationGuid=\"${app}\"}[1m])) by (applicationGuid, forwarder_instance_index)",
     "legendFormat": "{{applicationGuid}}/{{forwarder_instance_index}}"
    }
   ]
  },
  {
   "title": "Failed Event Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(cloudwatch_forwarder_output_num_events_failed{applicationGuid=\"${app}\"}[1m])) by (applicationGuid, forwarder_instance_index)",
     "legendFormat": "{{applicationGuid}}/{{forwarder_instance_index}}"
    }
   ]
  },
  { "title": "Uptime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Logging Uptime $noisy_app",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 14 },
   "repeat": "noisy_app",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(1 - (increase(noisy_num_events_failed{applicationGuid=~\"${noisy_app:regex}\"}[$__range]) / (increase(noisy_num_events_failed{applicationGuid=~\"${noisy_app:regex}\"}[$__range]) + increase(noisy_num_events_succeeded{applicationGuid=~\"${noisy_app:regex}\"}[$__range]))))"
    }
   ]
  },
  { "title": "Noisy $noisy_app", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 }, "repeat": "noisy_app" },
  {
   "title": "Target Generation Rate",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(max_over_time(noisy_target_event_rate{applicationGuid=~\"${noisy_app:regex}\"}[1m])) by (applicationGuid, applicationInstance)",
     "legendFormat": "{{applicationGuid}}:{{applicationInstance}}"
    }
   ]
  },
  {
   "title": "Generated Logs",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "increase(noisy_num_events_total{applicationGuid=~\"${noisy_app:regex}\"}[$__range]) ",
     "legendFormat": "{{applicationGuid}}/{{applicationInstance}}"
    }
   ]
  },
  {
   "title": "Successful Logs",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "increase(noisy_num_events_succeeded{applicationGuid=~\"${noisy_app:regex}\"}[$__range])",
     "legendFormat": "{{applicationGuid}}/{{applicationInstance}}"
    }
   ]
  },
  {
   "title": "Dropped Logs",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(noisy_num_events_failed{applicationGuid=~\"${noisy_app:regex}\"}[$__range])"
    }
   ]
  },
  {
   "title": "95th percentile latency",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(noisy_matching_latency_bucket{applicationGuid=~\"${noisy_app:regex}\"}[$__range])) by (applicationGuid, applicationInstance, le))",
     "legendFormat": "{{applicationGuid}}/{{applicationInstance}} 95th"
    }
   ]
  },
  {
   "title": "Success Rate",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (increase(noisy_num_events_failed{applicationGuid=~\"${noisy_app:regex}\"}[$__range]) / (increase(noisy_num_events_failed{applicationGuid=~\"${noisy_app:regex}\"}[$__range]) + increase(noisy_num_events_succeeded{applicationGuid=~\"${noisy_app:regex}\"}[$__range])))"
    }
   ]
  }
 ]
}