{
 "title": "Concourse",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "VM Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "system_cpu_user{job=\"concourse-deployment\"}",
     "legendFormat": "{{deployment}} {{exported_job}} {{index}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "system_mem_percent{job=\"concourse-deployment\"}",
     "legendFormat": "{{deployment}} {{exported_job}} {{index}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "system_disk_system_percent{job=\"concourse-deployment\"}",
     "legendFormat": "{{deployment}} {{exported_job}} {{index}}"
    }
   ]
  },
  {
   "title": "Network Egress",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(system_network_bytes_sent{job=\"concourse-deployment\"}[1m])",
     "legendFormat": "{{deployment}} {{exported_job}} {{index}}"
    }
   ]
  },
  {
   "title": "Network Ingress",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(system_network_bytes_received{job=\"concourse-deployment\"}[1m])",
     "legendFormat": "{{deployment}} {{exported_job}} {{index}}"
    }
   ]
  },
  {
   "title": "Health",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "system_healthy{job=\"concourse-deployment\"}",
     "legendFormat": "{{deployment}} {{exported_job}} {{index}}"
    }
   ]
  },
  { "title": "Worker Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Jobs Scheduling",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "concourse_jobs_scheduling" }
   ]
  },
  {
   "title": "Running Jobs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "concourse_builds_running" }
   ]
  },
  {
   "title": "Slow Jobs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(10, histogram_quantile(0.9, concourse_builds_duration_seconds_bucket))",
     "legendFormat": "{{pipeline}}/{{exported_job}}"
    }
   ]
  },
  {
   "title": "Job Success Rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(concourse_builds_finished_total - concourse_builds_failed_total) / (concourse_builds_finished_total)"
    }
   ]
  },
  {
   "title": "LIDAR Success Rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(rate(concourse_lidar_checks_finished_total[5m])) - sum(rate(concourse_lidar_checks_finished_total{status=\"error\"}[5m]))) / sum(rate(concourse_lidar_checks_finished_total[5m]))"
    }
   ]
  },
  {
   "title": "Frequent Jobs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, concourse_builds_duration_seconds_count)",
     "legendFormat": "{{pipeline}}/{{exported_job}}"
    }
   ]
  },
  { "title": "Web Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "95th percentile HTTP Response Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(concourse_http_responses_duration_seconds_bucket[1m]))",
     "legendFormat": "{{method}} {{route}} {{status}}"
    }
   ]
  },
  {
   "title": "LIDAR Check Queue Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "concourse_lidar_check_queue_size"
    }
   ]
  },
  {
   "title": "Tasks Waiting",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "concourse_tasks_waiting" }
   ]
  },
  {
   "title": "DB Queries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(concourse_db_queries_total[5m])"
    }
   ]
  },
  {
   "title": "DB Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "concourse_db_connections", "legendFormat": "{{dbname}}" }
   ]
  },
  {
   "title": "Database Locks Held",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "concourse_locks_held", "legendFormat": "{{type}}" }
   ]
  },
  { "title": "Containers and Volumes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Containers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "concourse_workers_containers", "legendFormat": "{{workers}}" }
   ]
  },
  {
   "title": "Volumes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "concourse_workers_volumes", "legendFormat": "{{worker}}" }
   ]
  }
 ]
}