{
 "title": "Fluentd",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Records processed per second",
   "type": "stat",
   "description": "Records processed for both input and output. Ideally, these should be the same number, but may occasionally fluctuate during high load.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(fluentd_input_status_num_records_total[5m])",
     "legendFormat": "Input"
    },
    {
     "expr": "rate(fluentd_output_status_num_records_total[5m])",
     "legendFormat": "Output"
    }
   ]
  },
  {
   "title": "Output Buffer Chunks",
   "type": "graph",
   "description": "The number of chunks of data currently buffered due to downstream backpressure. Ideally, this is 0, but it may occasionally spike for a short period during high log volume or if a consumer slows down.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fluentd_output_status_buffer_queue_length",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Output Retries",
   "type": "graph",
   "description": "The number of retries for each output type. This should ideally be 0, but may occasionally spike during heavy load.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "fluentd_status_retry_count", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "Output Buffer Size",
   "type": "graph",
   "description": "Size of each output buffer in bytes. The s3 buffer rotates every 1 GB, so it's normal to see it climb and fall every 1 GB.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "fluentd_output_status_buffer_total_bytes",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}