{
 "title": "Go Router traffic monitoring",
 "description": "Detection of burst traffic anomalies in Go Router",
 "time": { "from": "now-1d", "to": "now" },
 "panels": [
  { "title": "go router traffic statistics ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "go router packets per minute standard deviation",
   "type": "timeseries",
   "description": "Computed z_score > 3 for previous 5 minutes compared to past 24 hours.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "abs(\n    avg_over_time(total_requests{exported_job=~\"router\"}[5m])\n    - \n    avg_over_time(total_requests{exported_job=~\"router\"}[24h])\n)\n    / \n    stddev_over_time(total_requests{exported_job=~\"router\"}[24h])",
     "legendFormat": "{{exported_job}}//{{index}} z_score > 3"
    }
   ]
  },
  {
   "title": "Go Router Network Packets per Minute",
   "type": "timeseries",
   "description": "Stacked display of network packets per minute per GoRouter instance",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "increase(total_requests{exported_job=\"router\"}[1m]) / 1000",
     "legendFormat": "{{exported_job}}//{{index}}"
    }
   ]
  },
  {
   "title": "Go Router Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Go Router Logs",
     "type": "logs",
     "description": "Logs shows app deletions, app deployments, app-traffic, etc.",
     "gridPos": { "h": 22, "w": 24, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "{ident=~\"gorouter\"} | json | line_format `{{.message}}`",
       "legendFormat": "{{exported_job}}",
       "maxLines": 2000
      }
     ]
    }
   ]
  },
  {
   "title": "CC Audit Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "CC Audit Logs",
     "type": "logs",
     "description": "Cloud Controller Audit events show what is happening in the foundation",
     "gridPos": { "h": 26, "w": 24, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "{ident=\"system.system.cf-events-logger\"} != `GET /metrics` | json | line_format `{{.message}}`"
      }
     ]
    }
   ]
  }
 ]
}