{
 "title": "VM Health",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Cloud Init Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum(node_systemd_unit_state{name=\"cloud-init.service\",state=\"active\"})) / sum(up{job=\"ec2\"})",
     "legendFormat": "rsyslog"
    }
   ]
  },
  {
   "title": "RSyslog Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum(node_systemd_unit_state{name=\"rsyslog.service\",state=\"active\"})) / sum(up{job=\"ec2\"})",
     "legendFormat": "rsyslog"
    }
   ]
  },
  {
   "title": "Clam AV Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum(node_systemd_unit_state{name=\"clamd@scan.service\",state=\"active\"}) + sum(node_systemd_unit_state{name=\"clamav-daemon.service\",state=\"active\"})) / sum(up{job=\"ec2\"})",
     "legendFormat": "clamd"
    },
    {
     "expr": "(sum(node_systemd_unit_state{name=\"clam-freshclam.service\",state=\"active\"}) + sum(node_systemd_unit_state{name=\"clamav-freshclam.service\",state=\"active\"})) / sum(up{job=\"ec2\"})",
     "legendFormat": "freshclam"
    }
   ]
  },
  {
   "title": "Named Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{name_tag=~\".*bind\"} + on(name_tag, availability_zone) node_systemd_unit_state{name=\"named.service\",state=\"active\"}",
     "legendFormat": "{{name_tag}}"
    }
   ]
  },
  {
   "title": "Fluentd Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{name_tag=~\".*fluentd\"} + on(name_tag, availability_zone)  node_systemd_unit_state{name=\"td-agent.service\",state=\"active\"}",
     "legendFormat": "{{name_tag}}"
    },
    {}
   ]
  },
  {
   "title": "Essential Service Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum by (instance, name) (node_systemd_unit_state{name=~\"(td-agent|named|rsyslog|clamd@scan|clamav-daemon|clam-freshclam|clamav-freshclam|cloud-init).service\", state=\"active\"})) / (sum by (instance, name) (node_systemd_unit_state))",
     "legendFormat": "{{instance}} {{name}}"
    }
   ]
  }
 ]
}