{
 "title": "VM Resources",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "az",
    "label": "Availability Zone",
    "query": "label_values(up, availability_zone)"
   },
   { "name": "name", "label": "Name", "query": "label_values(up, name_tag)" }
  ]
 },
 "panels": [
  { "title": "Service Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Alert Status", "type": "alertlist", "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 } },
  {
   "title": "Failed Systemd Units",
   "type": "table",
   "description": "These services are reporting 'failed' in systemd.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(node_systemd_unit_state{availability_zone=~\"${az:regex}\",name_tag=~\"${name:regex}\",state=\"failed\"}) by (name_tag, availability_zone, name) > 0",
     "legendFormat": "{{name_tag}} - {{availability_zone}} - {{name}}"
    }
   ]
  },
  {
   "title": "Up Instances",
   "type": "table",
   "description": "TSDB is able to retrieve metrics from these instances, this means the instance is up and node_exporter is working. Check the systemd status to understand whether other services are working.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(up{availability_zone=~\"${az:regex}\",name_tag=~\"${name:regex}\"}) by (name_tag, availability_zone) > 0",
     "legendFormat": "{{name_tag}} - {{availability_zone}}"
    }
   ]
  },
  {
   "title": "Down Instances",
   "type": "table",
   "description": "TSDB is unable to retrieve metrics from these instances, this likely means the instance is not correctly configured.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum(up{availability_zone=~\"${az:regex}\",name_tag=~\"${name:regex}\"}) by (name_tag, availability_zone) < 1",
     "legendFormat": "{{name_tag}} - {{availability_zone}}"
    }
   ]
  },
  { "title": "VM Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - (avg by (instance, name_tag, availability_zone)  (irate(node_cpu_seconds_total{mode=\"idle\",name_tag=~\"${name:regex}\",availability_zone=~\"${az:regex}\"}[5m])))",
     "legendFormat": "{{name_tag}} - {{availability_zone}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes - node_memory_MemFree_bytes - (node_memory_Buffers_bytes + node_memory_Cached_bytes)) / node_memory_MemTotal_bytes{name_tag=~\"${name:regex}\",availability_zone=~\"${az:regex}\"})",
     "legendFormat": "{{name_tag}} - {{availability_zone}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg((node_filesystem_size_bytes{name_tag=~\"${name:regex}\",availability_zone=~\"${az:regex}\"} - node_filesystem_avail_bytes{name_tag=~\"${name:regex}\",availability_zone=~\"${az:regex}\"}) / node_filesystem_size_bytes{name_tag=~\"${name:regex}\",availability_zone=~\"${az:regex}\"}) by (name_tag, availability_zone, mountpoint)",
     "legendFormat": "{{name_tag}} - {{availability_zone}} - {{mountpoint}}"
    },
    {}
   ]
  },
  { "title": "Alert-Backing Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Missing Metrics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(1 - up{name_tag!=\"\"}) > 0",
     "legendFormat": "{{name_tag}} | {{availability_zone}}"
    }
   ]
  },
  {
   "title": "Failed Systemd Units",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_systemd_unit_state{state=\"failed\"} > 0",
     "legendFormat": "{{name_tag}} | {{availability_zone}} | {{name}}"
    }
   ]
  }
 ]
}