resources:

- name: terraforming
  type: git
  source:
    branch: master
    uri: git@github.com:pivotal-federal-field-engineering/terraforming-pws-dark.git
    private_key: ((eagle_bot_github_user_key))

jobs:
- name: key-master
  max_in_flight: 1
  plan:
  - get: terraforming
    trigger: true
  - task: key-master
    file: terraforming/ci/tasks/lifecycle.yml
    params:
      region: ((region))
      access_key: ((access_key))
      secret_key: ((secret_key))
      env_path: terraforming/env/dev/key-master

- name: vgw
  max_in_flight: 1
  plan:
    - get: terraforming
      trigger: true
    - task: vgw
      file: terraforming/ci/tasks/lifecycle.yml
      params:
        region: ((region))
        access_key: ((access_key))
        secret_key: ((secret_key))
        env_path: terraforming/env/dev/vgw

- name: air-gapped
  max_in_flight: 1
  plan:
    - get: terraforming
      trigger: true
    - task: air-gapped
      file: terraforming/ci/tasks/lifecycle.yml
      params:
        region: ((region))
        access_key: ((access_key))
        secret_key: ((secret_key))
        env_path: terraforming/env/dev/air-gapped

- name: bastion-airgapped
  max_in_flight: 1
  plan:
    - get: terraforming
      trigger: true
    - task: bastion-airgapped
      file: terraforming/ci/tasks/lifecycle.yml
      params:
        region: ((region))
        access_key: ((access_key))
        secret_key: ((secret_key))
        env_path: terraforming/env/dev/ops-sandbox/bastion-air-gapped

- name: bastion-vgw
  max_in_flight: 1
  plan:
    - get: terraforming
      trigger: true
    - task: bastion-vgw
      file: terraforming/ci/tasks/lifecycle.yml
      params:
        region: ((region))
        access_key: ((access_key))
        secret_key: ((secret_key))
        env_path: terraforming/env/dev/ops-sandbox/bastion-vgw
