resources:

- name: terraforming
  type: git
  source:
    uri: git@github.com:pivotal-federal-field-engineering/terraforming-aws.git
    private_key: ((eagle_bot_github_user.private_key))

jobs:
- name: key-master
  max_in_flight: 1
  plan:
  - get: terraforming
    trigger: true
  - task: key-master
    file: terraforming/ci/tasks/lifecycle.yml
    params:
      region: ((region))
      access_key: ((access_key))
      secret_key: ((secret_key))
      env_path: terraforming/env/dev/key-master

- name: vgw
  max_in_flight: 1
  plan:
    - get: terraforming
      trigger: true
    - task: vgw
      file: terraforming/ci/tasks/lifecycle.yml
      params:
        region: ((region))
        access_key: ((access_key))
        secret_key: ((secret_key))
        env_path: terraforming/env/dev/vgw

- name: combine
  max_in_flight: 1
  plan:
    - get: terraforming
      trigger: true
    - task: vgw
      file: terraforming/ci/tasks/lifecycle.yml
      params:
        region: ((region))
        access_key: ((access_key))
        secret_key: ((secret_key))
        env_path: terraforming/env/dev/combine

- name: ssh
  max_in_flight: 1
  plan:
    - get: terraforming
      trigger: true
    - task: vgw
      file: terraforming/ci/tasks/lifecycle.yml
      params:
        region: ((region))
        access_key: ((access_key))
        secret_key: ((secret_key))
        env_path: terraforming/env/dev/ssh

