= Isolation Segment Run book

== Adding a new Isolation Segment VPC

An isolation segment VPC is only able to host four isolation segments. The operator will have to carry out the steps in this section every fourth isolation segment.

. Request a new VPC
. Create an internet gateway or a virtual private gateway in the new VPC
. Create VPC peering between the new VPC and the following VPCs. Make sure the new VPC is the accepter, and the following VPCs are the requesters:
.. The PAS VPC
.. The Bastion VPC
.. The Enterprise Services VPC
. Create a new layer in the environment repo with the following name `bootstrap_isolation_segment_vpc_X,` where X is an incrementing identifier.
. Set the terragrunt.hcl content to match the following, where VPC_ID is the id of the vpc created in step 1:
+
----
include {
  path = "${find_in_parent_folders()}"
}

dependencies {
  paths = ["../pas"]
}

inputs = {
  nat_instance_type = "t2.small"
  vpc_id = "VPC_ID"
  isolation_segment_name_0 = ""
  isolation_segment_name_1 = ""
  isolation_segment_name_2 = ""
  isolation_segment_name_3 = ""
}
----

== Onboarding a new Isolation Segment

. Ensure there is a VPC that is setup properly to host an isolation segment by following the steps in the previous section.
. Find an unallocated isolation segment name in the bootstrap_isolation_segment layer. The isolation segment is unallocated if the value of `isolation_segment_name_X` is the empty string.
. Allocate the isolation segment by setting the variable value to the business unit name, mission name, etc. We will assume the isolation segment name is "Customer A ." For example, the `terragrunt.hcl` file from the previous section would change from:
+
----
inputs = {
  nat_instance_type = "t2.small"
  vpc_id = "VPC_ID"
  isolation_segment_name_0 = ""
----
+
to
+
----
inputs = {
  nat_instance_type = "t2.small"
  vpc_id = "VPC_ID"
  isolation_segment_name_0 = "Customer A"
----
. Create a new layer in the environment repo with the following name `customer-a-isolation-segment.`
+
NOTE: The layer name is the concatentation of the name used above and `-isolation-segment.` Prefixing the layer name like that isn't required but helps to keep track of the isolation segment usage.
. Inside the new layer, create a new file `terragrunt.hcl` with the following content.
+
----
include {
  path = "${find_in_parent_folders()}"
}

dependencies {
  paths = ["../bootstrap_control_plane", "../pas"]
}

inputs = {
  name = "Customer A"
}
----
+
WARNING: The value of the `name` variable must match the value used in step 3:
