
name: golangci-lint
on: [push]
jobs:

  golangci-0:
    name: lint modules/download_certs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          working-directory: modules/download_certs

