
name: golangci-lint
on: [push]
jobs:

  golangci-0:
    name: lint modules/download_certs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          working-directory: modules/download_certs

