
name: golangci-lint
on: [push]
jobs:

  golangci-0:
    name: lint modules/download_certs
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          working-directory: modules/download_certs
          args: --timeout 2m

