---
name: "create-release"

on: [push]

jobs:
  gh_pre_release:
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Extract Branch
        id: extract_branch
        shell: bash
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}"

      - name: Bump version and push tag
        id: version_bump
        uses: anothrNick/github-tag-action@v1
        env:
          WITH_V: false
          INITIAL_VERSION: 0.0.0
          DRY_RUN: true
          PRERELEASE_SUFFIX: "${{ steps.extract_branch.outputs.BRANCH }}"

      - name: Zip Source
        id: zip_source
        run: |
          zip -r ${{ github.event.repository.name }}-${{ steps.version_bump.outputs.new_tag }}.zip .

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: "${{ github.event.repository.name }}-${{ steps.version_bump.outputs.new_tag }}.zip"
          tag_name: "${{ steps.version_bump.outputs.new_tag }}"
          target_commitish: "${{ steps.extract_branch.outputs.BRANCH }}"
          prerelease: "${{ steps.extract_branch.outputs.BRANCH != 'master' }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

